package com.flagleader.repository.lang.expression;

import com.flagleader.repository.tree.RulePackage;
import com.flagleader.util.StringUtil;

public class h extends z
  implements g
{
  protected boolean a = false;
  protected boolean b = true;
  protected RulePackage c = null;
  protected static com.flagleader.repository.lang.h d = com.flagleader.repository.lang.b.i.d();
  protected boolean e = false;

  protected void a(RulePackage paramRulePackage)
  {
    c("the class file is generated by RuleBuilder. Copyright 2008-2010 flagleader ,  All Rights Reserved.");
    if (paramRulePackage.isValidPackage())
      b("package " + paramRulePackage.getPackageName() + ";");
    b("import com.flagleader.engine.*;");
    b("import com.flagleader.sql.*;");
    b("import com.flagleader.db.*;");
    b("import com.flagleader.xml.*;");
    b("import com.flagleader.util.*;");
    b("import com.flagleader.excel.*;");
    b("import java.util.*;");
    f();
  }

  private void c(String paramString)
  {
    this.e = true;
    b("/**");
    a(paramString, " * ");
    b(" */");
    this.e = false;
  }

  public boolean a()
  {
    return this.a;
  }

  public void a(boolean paramBoolean)
  {
    this.a = paramBoolean;
  }

  private void d(String paramString)
  {
    if (a())
      a("/* " + StringUtil.replace(g, "  ", paramString) + " */");
  }

  private String e(String paramString)
  {
    if (paramString.indexOf("\\") >= 0)
      paramString = StringUtil.replace("\\", "\\\\", paramString);
    if (paramString.indexOf("\"") >= 0)
      paramString = StringUtil.replace("\"", "\\\"", paramString);
    if (paramString.indexOf("\n") >= 0)
      paramString = StringUtil.replace("\n", "\\n", paramString);
    if (paramString.indexOf("\r") >= 0)
      paramString = StringUtil.replace("\r", "", paramString);
    return StringUtil.gbEncoding(paramString);
  }

  public Object a(b paramb)
  {
    i[] arrayOfi = paramb.c();
    for (int i = 0; i < arrayOfi.length; i++)
    {
      e();
      arrayOfi[i].a(this);
      f();
    }
    return null;
  }

  public Object a(c paramc)
  {
    j[] arrayOfj = paramc.c();
    for (int i = 0; i < arrayOfj.length; i++)
    {
      arrayOfj[i].a(this);
      f();
    }
    return null;
  }

  public Object a(i parami)
  {
    return null;
  }

  public Object a(j paramj)
  {
    return null;
  }

  public Object a(k paramk)
  {
    return null;
  }

  public Object a(l paraml)
  {
    return null;
  }

  public Object a(m paramm)
  {
    return null;
  }

  public Object a(n paramn)
  {
    return null;
  }

  public Object a(p paramp)
  {
    return null;
  }

  public Object a(q paramq)
  {
    return null;
  }

  public Object a(r paramr)
  {
    return null;
  }

  public Object a(s params)
  {
    return null;
  }

  public Object a(t paramt)
  {
    return null;
  }

  public Object a(u paramu)
  {
    return null;
  }

  public Object a(v paramv)
  {
    return null;
  }

  public Object a(w paramw)
  {
    return null;
  }

  public Object a(x paramx)
  {
    return null;
  }

  public Object a(y paramy)
  {
    return null;
  }

  public Object a(A paramA)
  {
    return null;
  }
}

/* Location:           D:\Dev_tools\ruleEngine\rbuilder.jar
 * Qualified Name:     com.flagleader.repository.lang.expression.h
 * JD-Core Version:    0.6.0
 */